# Generated by Django 4.0.6 on 2022-07-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrugs', '0002_alter_drug_durum_alter_drug_etken_alter_drug_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
