# Generated by Django 3.2.14 on 2022-07-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydrugs', '0003_alter_drug_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgkDrug',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('BARKOD', models.TextField(max_length=250, unique=True)),
                ('ILAC_ADI', models.TextField(max_length=250)),
                ('SGK_ILAC_KODU', models.TextField(max_length=250)),
                ('AMBALAJ_MIKTARI', models.FloatField()),
                ('TEK_DOZ_MIKTARI', models.FloatField()),
                ('DURUM', models.TextField(max_length=250)),
                ('AKTIF', models.BooleanField()),
            ],
        ),
    ]
